function net = initCnn()
%INITCNN Creates a CNN.

f=1/100 ;
net.layers = {};
net.layers{end+1} = struct(...
                           'name', 'conv1', ...
                           'type', 'conv', ...
                           'weights', {{f*randn(5,5,3,25, 'single'), f*randn(3, 25, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0);

net.layers{end+1} = struct(...
                           'name', 'max-pool1',...
                           'type', 'pool', ...
                           'method', 'max', ...
                           'pool', [3 3], ...
                           'stride', 2, ...
                           'pad', 0);

net.layers{end+1} = struct('type', 'relu');

net.layers{end+1} = struct(...
                           'name', 'conv2', ...
                           'type', 'conv', ...
                           'weights', {{f*randn(5,5,3,25, 'single'), f*randn(3, 25, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0);

net.layers{end+1} = struct('type', 'softmaxloss');

net = vl_simplenn(net);

end

