% TODO: load images in a datastore

% Input layer
% TODO: the size of the input layer should be set by parameters
probeInputLayer = imageInputLayer([128 48 3], ...
    'DataAugmentation', {'randfliplr', 'randcrop'}, ...
    'Name', 'Probe input layer');

galleryInputLayer = imageInputLayer([128 48 3], ...
    'DataAugmentation', {'randfliplr', 'randcrop'}, ...
    'Name', 'Gallery input layer');

% Convolutional layer
convLayer = convolution2dlayer(3, 25, ...
    'Stride', 1, ...
    'Padding', [1 1], ...
    'NumChannels', 3);

probeCnn = [probeInputLayer
    convLayer];